### ISSUE TITLE
Why don't add a hotkey to close the panels?

### ISSUE THREAD

**Issue by martinrhan** [ManlyMarco/RuntimeUnityEditor#12]
Firstly thank you for this plugin which provides great convenice to me.
But when I use it, it was once turned on cannot be turned off any more. It blocks the items of my game. Why isn't there a hotkey or button to close it?
Maybe there is such thing, please tell me if its true.

**Comment by ManlyMarco** [comment]
It's the same key you used to turn it on, by default it's F12.

**Comment by martinrhan** [comment]
> It's the same key you used to turn it on, by default it's F12.

Then some thing is wrong. I cannot turn it off by f12. Maybe its related to keys already occupied by the game? I will check it again tomorrow.

**Comment by ManlyMarco** [comment]
In new version of runtime editor you can hide the REPL window, but the browser window on the right will still open.
