### ISSUE TITLE
issue with RuntimeUnityEditor_BepInEx5_v2.1.zip

### ISSUE THREAD

**Issue by RichardB73** [ManlyMarco/RuntimeUnityEditor#15]
Hi, it seems there is an 0 bit file in the zip called plugins.
7-zip just hangs and gives an error that it cant find the files when i try to extract it.
Once i delete the plugins file from the archive it has no problem extracting it.
Hope it is not something only on my end.

**Comment by ManlyMarco** [comment]
Update 7-zip to latest version and try again.

**Comment by RichardB73** [comment]
Okay updating 7-zip fixed my issue, sorry to have bothered you with this and thank you for your fast reply.
