### ISSUE TITLE
Saving made changes in RuntimeUnityEditor.

### ISSUE THREAD

**Issue by sashaok123** [ManlyMarco/RuntimeUnityEditor#16]
Good afternoon, **ManlyMarco**!

We are modifying an already prepared project, there is no access to the sources.
Specifically, we are engaged in translation of already released games.

Is it possible to _save the changes_ made in **RuntimeUnityEditor** so that you can open and continue translation?

And how can we _apply_ them automatically when launching a project that used the **RuntimeUnityEditor**?

Thank you.

**Comment by ManlyMarco** [comment]
Hello!

It's not possible to save/load changes at the moment, and I don't plan to work on anything similar in the near future.

For translating a game you should use this plugin instead https://github.com/bbepis/XUnity.AutoTranslator and only use runtime editor as a development/testing tool.

**Comment by sashaok123** [comment]
**AutoTranslator** can't scale text :(
And the Russian language has a lot of long words.
For example, the word Quit - Output (Vihod) or Welcome - Welcome (Dobro pojalivat').

That's why we decided to use **RuntimeUnityEditor**, to scale and transform TextMesh.

**Comment by ManlyMarco** [comment]
AutoTranslator definitely can scale text, check its readme on how to do it.
