### ISSUE TITLE
Suggestion: Block Rewired input during typing

### ISSUE THREAD

**Issue by benediktwerner** [ManlyMarco/RuntimeUnityEditor#17]
It's pretty annoying when typing in the REPL and suddenly all kinds of things are happening in the background because the game also responds to the inputs. Unfortunately, it doesn't seem like there is a general way to prevent this in Unity but at least it should be possible to do for games using Rewired (any maybe also other input systems).

I'd be up to implement something like this but I wanted to ask first if that sounds like a good idea and it's something you would accept.

The only issue I can see is that it might not be that easy to determine when a user is focused in a text field so maybe an alternative in that case would be a button/toggle to disable all game input.

**Comment by benediktwerner** [comment]
Actually, it seems that in games not using Rewired the keyboard input is blocked correctly anyways, so this seems to be a Rewired specific issue.

**Comment by ManlyMarco** [comment]
The input blocking is the same as used in BepInEx.ConfigurationManager, so the fix would also be the same. It's weird that the inputs go through since they should be cleared every frame, that framework must be doing something unusual with how it gets the keys. It might be easier to make a separate plugin/script that patches rewired to not do that. Maybe disable its inputs if mouse cursor is over an IMGUI window.

**Comment by benediktwerner** [comment]
Ok, I guess blocking rewired would require some nasty reflection or a dependency on it in some form which indeed doesn't sound ideal. I now just created a simple Plugin which disables Rewired's keyboard input when Unity reports a UI element has keyboard control: https://github.combenediktwerner/RewiredBlocker

**Comment by ManlyMarco** [comment]
Both of these plugins call `Input.ResetInputAxes` every frame when mouse cursor is over their windows. Config manager also places an extra ongui window underneath to catch stray clicks. Rewired is the only case where this is not enough that I've seen so far.
