### ISSUE TITLE
"Failed to load REPL - Operation is not supported on this platform."

### ISSUE THREAD

**Issue by nedsociety** [ManlyMarco/RuntimeUnityEditor#20]
Tried to enable REPL and it failed with warning as in title. Is there an undocumented requirement for REPL to be active?

The game in context is [Monster Train](https://store.steampowered.com/app/1102190/Monster_Train/) if it helps.

**Comment by ManlyMarco** [comment]
REPL needs reflection emit to be available. Net Core games usually don't have it so REPL won't work in them.

**Comment by nedsociety** [comment]
I see. dnSpy integration won't help the situation, right?
