### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Yoyojojo12** [ManlyMarco/RuntimeUnityEditor#26]
Hello I have tested this on a game called Torque Drift and I'm pretty sure that it is on the Unity engine but it didn't work I have copied all of the bepinex files and made a plugins folder. How can I fix this?
Sorry to bother.

Thanks.

**Comment by ManlyMarco** [comment]
Check game log to see if bepinex and the plugin loads.

**Comment by Yoyojojo12** [comment]
![image](https://user-images.githubusercontent.com/91679152/159992416-e8822cb4-5125-4204-bfe6-c7d3fb1cadcc.png)

**Comment by ManlyMarco** [comment]
That's a bepinex changelog, not game log. Look for output_log.txt, it can be in different places depending on unity engine version and in some cases might be disabled. Check the bepinex wiki for more info https://docs.bepinex.dev/articles/user_guide/installation/index.html

**Comment by Yoyojojo12** [comment]
I don't have it for some reason

**Comment by ManlyMarco** [comment]
Closing as stale
