### ISSUE TITLE
Export objects/humanorids (with animation) as GLTF

### ISSUE THREAD

**Issue by ghost** [ManlyMarco/RuntimeUnityEditor#27]
Found a nice [rumtime recorder](
https://github.com/prefrontalcortex/UnityGLTF/blob/master/UnityGLTF/Assets/UnityGLTF/Runtime/Scripts/Timeline/GLTFRecorder.cs#L234) that can bake mesh, textures and animation into GLTF file, which can be imported in blender or other software for rendering.

I think it would be nice to debug some animation related issue if it could be integrated into RuntimeUnityEditor

**Comment by ManlyMarco** [comment]
I'm not particularly into the idea of dumping models, but if someone makes a PR for it I'll probably merge it.
