### ISSUE TITLE
Very low fps on Subnautica 2.0

### ISSUE THREAD

**Issue by HenryJk** [ManlyMarco/RuntimeUnityEditor#34]
When runtime editor shows on screen, the fps goes down to single digit. This does not happen on a popular [fork](https://github.com/brett-taylor/SubnauticaRuntimeUnityEditor) of RuntimeEditor for subnautica. Subnautica the game has just been updated in a way that breaks most mods also so this fork does not work on latest version of subnautica either.

**Comment by ManlyMarco** [comment]
Can you send the game log when runtime editor is running?

**Comment by ManlyMarco** [comment]
I tried it with the latest version and the performance impact wasn't that heavy even with everything open at once. Make sure you are using latest versions of everything.

![Annotation 2022-12-21 140350](https://user-images.githubusercontent.com/39247311/208912018-014154e1-7ad8-4df0-a4a3-662c334ccedc.jpg)

Please reopen the issue and let me know exactly how to reproduce the issue if it persists.

**Comment by HenryJk** [comment]
The slowdown only happen on gameplay, not on main menu. After retesting it, I find out that only Object Browser create this slowdown, attached is my save file you can try and a screenshot 
[SavedGames.zip](https://github.com/ManlyMarco/RuntimeUnityEditor/files/10278772/SavedGames.zip)
![Screenshot from 2022-12-21 22-01-58](https://user-images.githubusercontent.com/25541369/208936093-a7466f9e-27b2-440b-997d-6fb891d181e3.png)

**Comment by ManlyMarco** [comment]
Can you test if this build fixes the performance issues for you? [rue test list optimization.zip](https://github.com/ManlyMarco/RuntimeUnityEditor/files/10285927/rue.test.list.optimization.zip)

**Comment by ManlyMarco** [comment]
Improved version  [rue test list optimization 2.zip](https://github.com/ManlyMarco/RuntimeUnityEditor/files/10286340/rue.test.list.optimization.2.zip)
Changes: 6809995bb19d397a98c0e9a432db98dc77be7c32 2d38fdf6cf850366c28d662993ad663a7426948a

**Comment by HenryJk** [comment]
Problem gone, thank you
