### ISSUE TITLE
Why am I not responding when I press I and R, and displaying the recipe and item's Proto?

### ISSUE THREAD

**Issue by mczz25** [ManlyMarco/RuntimeUnityEditor#36]
I have installed LDBTool] and the log shows "Failed to initialize REPL environment - Operation is not supported on this platform." I am a newbie, can anyone tell me why?

**Comment by ManlyMarco** [comment]
No idea what LDBTool is and what game you're talking about. The warning is what it is, the REPL feature can't be used because it's not supported by whatever unity version that the game is using. No problems here.
