### ISSUE TITLE
2022 compile issues.

### ISSUE THREAD

**Issue by dimentox** [ManlyMarco/RuntimeUnityEditor#54]
Looksd like the extensions are making its not compile. also in cities 2 the f12 hook is not working.

**Comment by ManlyMarco** [comment]
Works fine on my PC. Clone a clean copy and show the errors.

**Comment by ManlyMarco** [comment]
![image](https://github.com/ManlyMarco/RuntimeUnityEditor/assets/39247311/f75b9fa4-a423-49a9-8ae5-ee9b0d487211)

**Comment by Cgameworld** [comment]
When installing from releases, opening the panel with f12 also is broken for me in Cities Skylines 2

**Comment by ManlyMarco** [comment]
@Cgameworld Did you try enabling hiding the manager object in bepinex.cfg?

**Comment by Cgameworld** [comment]
No, changing `HideManagerGameObject` to `true` in bepinex.cfg solved the issue.

Thanks for your help

**Comment by ManlyMarco** [comment]
That solves it I guess.
