### ISSUE TITLE
ReflectionTypeLoadException - RuntimeUnityEditorCore.dll

### ISSUE THREAD

**Issue by arnavoke** [ManlyMarco/RuntimeUnityEditor#59]
![image_2023-12-11_221633240](https://github.com/ManlyMarco/RuntimeUnityEditor/assets/69069296/eea05547-0e84-40d3-872e-7d0d5baf90bb)

I am trying to get RuntimeUnityEditor to run with a new game. I have unity mod manager installed i wrote a small test mod and its working fine. I am able to interact with game objects and scripts.
This game does not have a profile in the UMM list, so I selected derail valley as I have only that game with me rn from the list, looked at assembly code of new game with dnSpy and replaced the injection, starting and ui points for UMM. This was successful and I am able to start writing my working mods.

But for some reason no UnityRuntimeEditor won't load the core module [Error Snapshot attached above}. I tried using source code to build the project myself, I also got the mcs project, but while re refrencing some nuget packages i have to update them.
I even copied all the referenced dlls from all projects to the mod folder, still no luck

I checked RuntimeEditor on derail valley and it runs perfectly fine with it.

Can you help me with this? Thanks

**Comment by ManlyMarco** [comment]
If it works in another game then whatever game you are trying to run it on is probably missing some managed assemblies. You can copy them from managed folder of a different game that runs a similar version of unity to either the runtime editor folder or the game's own managed folder.

**Comment by arnavoke** [comment]
I didn't have a game with similar unity version, so i downloaded the same editor version, build the sample scene copied the libs to mod folder, managed one only was missing visual scripting (no relation with this ig). It still didn't work.
In the Bipinx section on homepage i read that if you get Loadedexception ,copy the core dll to managed folder, and that worked.

The mod loaded but failed to initialize REPL environment, so similarly i copied all mono libs to managed and now the mod is loading fine!!

Thanks for the direction and help!
